### ISSUE TITLE
大佬.新版本b服pc用不了fhx，会报错

### ISSUE THREAD

**Issue by ws380409397** [yekehui001/HarmoniousYJSWS#1]

**Comment by yekehui001** [comment]
PC客户端需要更新，否则会显示协议不匹配。
官服更新是用/Launcher/PDLauncher.exe启动游戏，用工具的话会自动选择。我不清楚B服要怎么更新。
记得更新前要点一下还原

**Comment by yekehui001** [comment]
转自B战官方号：亲爱的老板，可以添加QQ群：623841562 来获得B站PC端的方法哦~
