### ISSUE TITLE
dalao,以后还会像以前一样单独更新角色日语文件吗

### ISSUE THREAD

**Issue by Antique01** [yekehui001/HarmoniousYJSWS#3]
我用的是三种语言混合的语音包，因为不知道角色英文拼写所以很难从所有语音文件里筛选出想要的角色或皮肤语音文件。但是之前每次日服更新新角色这里都会更新当期的新语音文件，每个包文件数量都很少所以可以很轻松找到想要的文件。求问一下还能用以前那种方式更新吗？（不能也无所谓，有的用已经很知足了）

**Comment by yekehui001** [comment]
你要找谁的？
其实命名很有规律，稍微猜几个就能分出谁是谁了。

**Comment by Antique01** [comment]
西格玛，嘉恩小林的新年皮

**Comment by yekehui001** [comment]
西格玛：*_ras_tower
小林新年：*_alt_xiaolin_newyear2021
嘉恩新年：*_hb_gaeun_newyear2021

**Comment by Antique01** [comment]
谢谢大佬！
